### ISSUE TITLE
Fix the readme

### ISSUE THREAD

**Issue by srekcud** [Cryde/musicall#504]
There is a dead link in the readme into the JWT section , so it's impossible to install and use the repo on local

**Comment by Cryde** [comment]
It should be fix now !

**Comment by srekcud** [comment]
![image](https://user-images.githubusercontent.com/12445827/215032220-0cc438ae-8a45-4349-ae4d-a1c5d2908beb.png)

**Comment by srekcud** [comment]
Nope still not
